.PHONY: all tarprep distclean clean clean-tarprep cleandeps

all: $(sort ${TARGETS})

tarprep: $(sort ${TARTARGETS})

distclean:: clean
	@${LIBTOOL} --quiet --mode=clean rm -f ${DISTCLEANTARGETS}

clean:: clean-tarprep
	@${LIBTOOL} --mode=clean rm -f $(sort ${CLEANTARGETS})

clean-tarprep::
	@${LIBTOOL} --quiet --mode=uninstall rm -f $(sort ${TARTARGETS})

cleandeps::
	@${LIBTOOL} --quiet --mode=clean rm -f ${DEPSTARGETS}

