.TH "Dwm::XDRUtils" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::XDRUtils \- Wrapper for XDR encode/decode functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmXDRUtils\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBEncode\fP (float val, std::array< char, 4 > &buf)"
.br
.RI "Encode the given float \fRval\fP into the given buffer \fRbuf\fP\&. "
.ti -1c
.RI "static bool \fBDecode\fP (const std::array< char, 4 > &buf, float &val)"
.br
.RI "Decodes the given buffer \fRbuf\fP into the given value \fRval\fP\&. "
.ti -1c
.RI "static bool \fBEncode\fP (double val, std::array< char, 8 > &buf)"
.br
.RI "Encode the given double \fRval\fP into the given buffer \fRbuf\fP\&. "
.ti -1c
.RI "static bool \fBDecode\fP (const std::array< char, 8 > &buf, double &val)"
.br
.RI "Decodes the given buffer \fRbuf\fP into the given double value \fRval\fP\&. "
.ti -1c
.RI "static uint32_t \fBEncode\fP (float val, char **buf)"
.br
.RI "Encodes the given float \fRval\fP into \fR*buf\fP\&. "
.ti -1c
.RI "static void \fBDecode\fP (char *buf, float &val)"
.br
.RI "Decodes the given \fRbuf\fP into the given float value \fRval\fP\&. "
.ti -1c
.RI "static uint32_t \fBEncode\fP (double val, char **buf)"
.br
.RI "Encodes the given double \fRval\fP into \fR*buf\fP\&. "
.ti -1c
.RI "static void \fBDecode\fP (char *buf, double &val)"
.br
.RI "Decodes the given \fRbuf\fP into the given double value \fRval\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Wrapper for XDR encode/decode functions\&. 
.SH "Member Function Documentation"
.PP 
.SS "static bool Dwm::XDRUtils::Decode (const std::array< char, 4 > & buf, float & val)\fR [static]\fP"

.PP
Decodes the given buffer \fRbuf\fP into the given value \fRval\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::XDRUtils::Decode (const std::array< char, 8 > & buf, double & val)\fR [static]\fP"

.PP
Decodes the given buffer \fRbuf\fP into the given double value \fRval\fP\&. Returns true on success, false on failure\&. 
.SS "static uint32_t Dwm::XDRUtils::Encode (double val, char ** buf)\fR [static]\fP"

.PP
Encodes the given double \fRval\fP into \fR*buf\fP\&. If \fR*buf\fP is non-null on entry, it will be freed\&. \fR*buf\fP will be allocated to hold the encoded value\&. Returns the size of *buf\&. 
.SS "static bool Dwm::XDRUtils::Encode (double val, std::array< char, 8 > & buf)\fR [static]\fP"

.PP
Encode the given double \fRval\fP into the given buffer \fRbuf\fP\&. Returns true on success, false on failure\&. 
.SS "static uint32_t Dwm::XDRUtils::Encode (float val, char ** buf)\fR [static]\fP"

.PP
Encodes the given float \fRval\fP into \fR*buf\fP\&. If \fR*buf\fP is non-null on entry, it will be freed\&. \fR*buf\fP will be allocated to hold the encoded value\&. Returns the size of *buf\&. 
.SS "static bool Dwm::XDRUtils::Encode (float val, std::array< char, 4 > & buf)\fR [static]\fP"

.PP
Encode the given float \fRval\fP into the given buffer \fRbuf\fP\&. Returns true on success, false on failure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
