.TH "Dwm::StreamReadable" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::StreamReadable \- This class defines an interface for classes that can read their contents from an istream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmStreamIOCapable\&.hh>\fP
.PP
Inherited by \fBDwm::Readable\fP, and \fBDwm::StreamIOCapable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~StreamReadable\fP ()"
.br
.RI "destructor "
.ti -1c
.RI "virtual std::istream & \fBRead\fP (std::istream &is)=0"
.br
.RI "Read from an istream\&. Return the istream\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class defines an interface for classes that can read their contents from an istream\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual std::istream & Dwm::StreamReadable::Read (std::istream & is)\fR [pure virtual]\fP"

.PP
Read from an istream\&. Return the istream\&. 
.PP
Implemented in \fBDwm::IpAddress\fP, \fBDwm::Ipv4Address\fP, \fBDwm::Ipv4PacketHeader\fP, \fBDwm::Ipv4Prefix\fP, \fBDwm::Ipv4Routes< _valueT >\fP, \fBDwm::Ipv4TcpHeader\fP, \fBDwm::Ipv4TcpPacket\fP, \fBDwm::Ipv4UdpHeader\fP, \fBDwm::Ipv4UdpPacket\fP, \fBDwm::Ipv6Address\fP, \fBDwm::Ipv6AddrMap< T, Hash >\fP, \fBDwm::Ipv6Prefix\fP, \fBDwm::Ipv6PrefixMap< T, Hash >\fP, \fBDwm::MacAddress\fP, \fBDwm::MplsLabel\fP, \fBDwm::MplsLabelStack\fP, \fBDwm::Patricia< KeyType, ValueType, KeyEqual >\fP, \fBDwm::Rusage\fP, \fBDwm::TimeInterval64\fP, \fBDwm::TimeInterval\fP, \fBDwm::TimeValue64\fP, and \fBDwm::TimeValue\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
