.TH "Dwm::StreamIOCapable" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::StreamIOCapable \- Interface for classes with iostream read and write capabilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmStreamIOCapable\&.hh>\fP
.PP
Inherits \fBDwm::StreamReadable\fP, and \fBDwm::StreamWritable\fP\&.
.PP
Inherited by \fBDwm::IpAddress\fP, Dwm::IpPrefix, \fBDwm::Ipv4Address\fP, \fBDwm::Ipv4PacketHeader\fP, \fBDwm::Ipv4Prefix\fP, \fBDwm::Ipv4Routes< _valueT >\fP, \fBDwm::Ipv4TcpHeader\fP, \fBDwm::Ipv4TcpPacket\fP, \fBDwm::Ipv4UdpHeader\fP, \fBDwm::Ipv4UdpPacket\fP, \fBDwm::Ipv6AddrMap< T, Hash >\fP, \fBDwm::Ipv6Address\fP, \fBDwm::Ipv6Prefix\fP, \fBDwm::Ipv6PrefixMap< T, Hash >\fP, \fBDwm::MacAddress\fP, \fBDwm::MplsLabel\fP, \fBDwm::MplsLabelStack\fP, \fBDwm::Patricia< KeyType, ValueType, KeyEqual >\fP, Dwm::ProcessInfo, \fBDwm::Rusage\fP, \fBDwm::TimeInterval\fP, \fBDwm::TimeInterval64\fP, \fBDwm::TimeValue\fP, and \fBDwm::TimeValue64\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBDwm::StreamReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamReadable\fP ()"
.br
.RI "destructor "
.ti -1c
.RI "virtual std::istream & \fBRead\fP (std::istream &is)=0"
.br
.RI "Read from an istream\&. Return the istream\&. "
.in -1c

Public Member Functions inherited from \fBDwm::StreamWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamWritable\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual std::ostream & \fBWrite\fP (std::ostream &os) const =0"
.br
.RI "Write to an ostream\&. Return the ostream\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for classes with iostream read and write capabilities\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
