.TH "Dwm::Readable" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Readable \- This class defines an interface for classes that can read their contents from an istream, file descriptor or FILE pointer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmReadable\&.hh>\fP
.PP
Inherits \fBDwm::DescriptorReadable\fP, \fBDwm::FileReadable\fP, and \fBDwm::StreamReadable\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBDwm::DescriptorReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~DescriptorReadable\fP ()"
.br
.RI "destructor "
.ti -1c
.RI "virtual ssize_t \fBRead\fP (int fd)=0"
.br
.RI "Read from a file descriptor\&. "
.in -1c

Public Member Functions inherited from \fBDwm::FileReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~FileReadable\fP ()"
.br
.RI "destructor "
.ti -1c
.RI "virtual size_t \fBRead\fP (FILE *f)=0"
.br
.RI "Read from a FILE pointer\&. "
.in -1c

Public Member Functions inherited from \fBDwm::StreamReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamReadable\fP ()"
.br
.RI "destructor "
.ti -1c
.RI "virtual std::istream & \fBRead\fP (std::istream &is)=0"
.br
.RI "Read from an istream\&. Return the istream\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class defines an interface for classes that can read their contents from an istream, file descriptor or FILE pointer\&. 

Note that this class is deprecated as of libDwm-0\&.8\&.0, and is now just a trivial grouping of \fBDescriptorReadable\fP, \fBFileReadable\fP and \fBStreamReadable\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
