.TH "Dwm::AreFFI_Dividable" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::AreFFI_Dividable \- T1 can be divided by T2 and yield a T1\&. i\&.e\&. { T1 / T2 } -> T1\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmFFIVar\&.hh>\fP
.SH "Concept definition"
.PP 

.nf
template<typename T1, typename T2>
concept Dwm::AreFFI_Dividable =  requires(T1 a, T2 b) {
    { a / b } \-> std::same_as<T1>;
  }
.PP
.fi
.SH "Detailed Description"
.PP 
T1 can be divided by T2 and yield a T1\&. i\&.e\&. { T1 / T2 } -> T1\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
