.TH "Dwm::DaemonUtils" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::DaemonUtils \- Tiny collection of utilities for daemon processes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmDaemonUtils\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDaemonize\fP ()"
.br
.RI "Become a daemon\&. "
.in -1c
.SH "Detailed Description"
.PP 
Tiny collection of utilities for daemon processes\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void Dwm::DaemonUtils::Daemonize ()\fR [static]\fP"

.PP
Become a daemon\&. Fork, disassociate from process group, ignore terminal I/O signals, disassociate from control terminal, close stdin and stdout\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
