.TH "Dwm::Base64Url" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Base64Url \- RFC 4648 base64 enconding and decoding functions for URLs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmBase64\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBEncode\fP (const std::string &s)"
.br
.RI "Returns a base64url encoded version of \fRs\fP\&. "
.ti -1c
.RI "static std::string \fBDecode\fP (const std::string &s)"
.br
.RI "Returns a decoded string for the base64url-encoded string \fRs\fP on success, an empty string on failure\&. "
.ti -1c
.RI "static std::ostream & \fBEncode\fP (std::istream &is, std::ostream &os)"
.br
.RI "Base64url encodes the contents of istream \fRis\fP into the ostream @ c os\&. "
.ti -1c
.RI "static std::ostream & \fBDecode\fP (std::istream &is, std::ostream &os)"
.br
.RI "Decodes the base64url encoded contents of istream \fRis\fP into the ostream \fRos\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
RFC 4648 base64 enconding and decoding functions for URLs\&. 

Uses the alphabet from Table 2 of RFC 4648\&. 
.SH "Member Function Documentation"
.PP 
.SS "static std::ostream & Dwm::Base64Url::Decode (std::istream & is, std::ostream & os)\fR [static]\fP"

.PP
Decodes the base64url encoded contents of istream \fRis\fP into the ostream \fRos\fP\&. Returns the ostream \fRos\fP\&. Note that the failbit will be set on both streams on failure\&. A typical cause of failure would be an invalid character in the input stream \fRis\fP\&. 
.SS "static std::ostream & Dwm::Base64Url::Encode (std::istream & is, std::ostream & os)\fR [static]\fP"

.PP
Base64url encodes the contents of istream \fRis\fP into the ostream @ c os\&. Returns the ostream \fRos\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
