.TH "Dwm::AssertionCounter" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::AssertionCounter \- Holds 'passed' and 'failed' counters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmUnitAssert\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertionCounter\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "uint64_t \fBFailed\fP () const"
.br
.RI "Returns the failed counter\&. "
.ti -1c
.RI "uint64_t \fBPassed\fP () const"
.br
.RI "Returns the passed counter\&. "
.ti -1c
.RI "void \fBAddFailed\fP ()"
.br
.RI "Increments the failed counter\&. "
.ti -1c
.RI "void \fBAddPassed\fP ()"
.br
.RI "Increments the passed counter\&. "
.ti -1c
.RI "\fBAssertionCounter\fP & \fBoperator+=\fP (const \fBAssertionCounter\fP &assertionCounter)"
.br
.RI "operator += "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBAssertionCounter\fP &assertionCounter)"
.br
.RI "Prints to an ostream\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds 'passed' and 'failed' counters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
