.TH "Dwm::ASIO" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::ASIO \- A collection of functions for reading from and writing to Boost \fBASIO\fP stream sockets\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmASIO\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, uint8_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, uint8_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, uint8_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, uint8_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, uint8_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, uint8_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, bool &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, bool value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, bool &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, bool value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, bool &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, bool value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, uint16_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, uint16_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, uint16_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, uint16_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, uint16_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, uint16_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, uint32_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, uint32_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, uint32_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, uint32_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, uint32_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, uint32_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, uint64_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, uint64_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, uint64_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, uint64_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, uint64_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, uint64_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, int8_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, int8_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, int8_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, int8_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, int8_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, int8_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, int16_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, int16_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, int16_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, int16_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, int16_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, int16_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, int32_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, int32_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, int32_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, int32_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, int32_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, int32_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, int64_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, int64_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, int64_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, int64_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, int64_t &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, int64_t value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, std::string &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, const std::string &value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, std::string &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, const std::string &value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, std::string &value, boost::system::error_code &ec)"
.br
.RI "Reads \fRvalue\fP from the given socket \fRs\fP\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, const std::string &value, boost::system::error_code &ec)"
.br
.RI "Write \fRvalue\fP to the given socket \fRs\fP\&. "
.ti -1c
.RI "static uint64_t \fBStreamedLength\fP (const std::string &s)"
.br
.RI "Returns the number of bytes that should be written if we call the \fBWrite()\fP member for a string\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, float &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, float val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, float &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, float val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, float &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, float val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::ip::tcp::socket &s, double &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::ip::tcp::socket &s, double val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::local::stream_protocol::socket &s, double &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::local::stream_protocol::socket &s, double val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBRead\fP (boost::asio::generic::stream_protocol::socket &s, double &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "static bool \fBWrite\fP (boost::asio::generic::stream_protocol::socket &s, double val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. "
.ti -1c
.RI "template<typename S , typename _firstT , typename _secondT > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::pair< _firstT, _secondT > &p, boost::system::error_code &ec)"
.br
.RI "Reads a pair<_firstT,_secondT> from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _firstT , typename _secondT > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::pair< _firstT, _secondT > &p, boost::system::error_code &ec)"
.br
.RI "Writes a pair<_firstT,_secondT> to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename\&.\&.\&. Args> 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::tuple< Args\&.\&.\&. > &t, boost::system::error_code &ec)"
.br
.RI "Reads a tuple from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename\&.\&.\&. Args> 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::tuple< Args\&.\&.\&. > &t, boost::system::error_code &ec)"
.br
.RI "Writes a tuple to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename\&.\&.\&. Ts> 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::variant< Ts\&.\&.\&. > &v, boost::system::error_code &ec)"
.br
.RI "Reads a variant \\C V from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename\&.\&.\&. Ts> 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::variant< Ts\&.\&.\&. > &v, boost::system::error_code &ec)"
.br
.RI "Writes a variant \fRv\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , size_t N> 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::array< _valueT, N > &a, boost::system::error_code &ec)"
.br
.RI "Reads an array<_valueT,N> \fRv\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , size_t N> 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::array< _valueT, N > &a, boost::system::error_code &ec)"
.br
.RI "Writes an array<_valueT\&.N> \fRv\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::vector< _valueT, _Alloc > &v, boost::system::error_code &ec)"
.br
.RI "Reads a vector<_valueT> \fRv\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::vector< _valueT, _Alloc > &v, boost::system::error_code &ec)"
.br
.RI "Writes a vector<_valueT> \fRv\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::deque< _valueT, _Alloc > &d, boost::system::error_code &ec)"
.br
.RI "Reads a deque<_valueT> \fRd\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::deque< _valueT, _Alloc > &d, boost::system::error_code &ec)"
.br
.RI "Writes a deque<_valueT> \fRd\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::list< _valueT, _Alloc > &l, boost::system::error_code &ec)"
.br
.RI "Reads a list<_valueT> \fRl\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::list< _valueT, _Alloc > &l, boost::system::error_code &ec)"
.br
.RI "Writes a list<_valueT> \fRl\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::map< _keyT, _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Reads a map<_keyT,_valueT> \fRm\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::map< _keyT, _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Writes a map<_keyT,_valueT> \fRm\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::multimap< _keyT, _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Reads a multimap<_keyT,_valueT> \fRm\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::multimap< _keyT, _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Writes a multimap<_keyT,_valueT> \fRm\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _keyT , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::unordered_map< _keyT, _valueT, _Hash, _Pred, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Reads an unordered_map<_keyT,_valueT> \fRm\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _keyT , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::unordered_map< _keyT, _valueT, _Hash, _Pred, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Writes a unordered_map<_keyT,_valueT> \fRm\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::set< _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Reads a set<_valueT> \fRm\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::set< _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Writes a set<_valueT> \fRm\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::multiset< _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Reads a multiset<_valueT> \fRm\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::multiset< _valueT, _Compare, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Writes a multiset<_valueT> \fRm\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, std::unordered_set< _valueT, _Hash, _Pred, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Reads an unordered_set<_valueT> \fRm\fP from \fRs\fP\&. "
.ti -1c
.RI "template<typename S , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const std::unordered_set< _valueT, _Hash, _Pred, _Alloc > &m, boost::system::error_code &ec)"
.br
.RI "Writes a unordered_set<_valueT> \fRm\fP to \fRs\fP\&. "
.ti -1c
.RI "template<typename S > 
.br
requires IsSupportedASIOSocket<S>static bool \fBRead\fP (S &s, \fBASIOReadable\fP &val, boost::system::error_code &ec)"
.br
.RI "Reads \fRval\fP from \fRs\fP\&. Returns true on success, false on failure\&. "
.ti -1c
.RI "template<typename S > 
.br
requires IsSupportedASIOSocket<S>static bool \fBWrite\fP (S &s, const \fBASIOWritable\fP &val, boost::system::error_code &ec)"
.br
.RI "Writes \fRval\fP to \fRs\fP\&. Returns true on success, false on failure\&. "
.ti -1c
.RI "template<typename S , typename\&.\&.\&. Args> 
.br
requires IsSupportedASIOSocket<S>static bool \fBReadV\fP (S &s, boost::system::error_code &ec, Args &\&.\&.\&.args)"
.br
.RI "Reads \fRargs\fP from \fRs\fP\&. Returns true on success, false on failure\&. "
.ti -1c
.RI "template<typename S , typename\&.\&.\&. Args> 
.br
requires IsSupportedASIOSocket<S>static bool \fBWriteV\fP (S &s, boost::system::error_code &ec, const Args &\&.\&.\&.args)"
.br
.RI "Writes \fRargs\fP to \fRs\fP\&. Returns true on success, false on failure\&. "
.in -1c
.SH "Detailed Description"
.PP 
A collection of functions for reading from and writing to Boost \fBASIO\fP stream sockets\&. 

TODO: I should probably redesign this\&. Initially I was only using sockets of type boost::asio::ip::tcp::socket\&. Once I needed support for boost::asio::local::stream_protocol::socket, things got messy\&. boost::asio doesn't have a class heirarchy here, it's all templatized\&. At the moment I don't have time to templatize or switch to only supporting generic::stream_protocol\&. 
.SH "Member Function Documentation"
.PP 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, bool & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, double & val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, float & val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, int16_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, int32_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, int64_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, int8_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, std::string & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, uint16_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, uint32_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, uint64_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::generic::stream_protocol::socket & s, uint8_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, bool & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, double & val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, float & val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, int16_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, int32_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, int64_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, int8_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, std::string & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, uint16_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, uint32_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, uint64_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::ip::tcp::socket & s, uint8_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, bool & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, double & val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, float & val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRval\fP from \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, int16_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, int32_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, int64_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, int8_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, std::string & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, uint16_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, uint32_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, uint64_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Read (boost::asio::local::stream_protocol::socket & s, uint8_t & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Reads \fRvalue\fP from the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "template<typename S , typename _valueT , size_t N> 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::array< _valueT, N > & a, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads an array<_valueT,N> \fRv\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::deque< _valueT, _Alloc > & d, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a deque<_valueT> \fRd\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::list< _valueT, _Alloc > & l, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a list<_valueT> \fRl\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::map< _keyT, _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a map<_keyT,_valueT> \fRm\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::multimap< _keyT, _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a multimap<_keyT,_valueT> \fRm\fP from \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::multiset< _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a multiset<_valueT> \fRm\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _firstT , typename _secondT > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::pair< _firstT, _secondT > & p, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a pair<_firstT,_secondT> from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::set< _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a set<_valueT> \fRm\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename\&.\&.\&. Args> 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::tuple< Args\&.\&.\&. > & t, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a tuple from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _keyT , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::unordered_map< _keyT, _valueT, _Hash, _Pred, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads an unordered_map<_keyT,_valueT> \fRm\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::unordered_set< _valueT, _Hash, _Pred, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads an unordered_set<_valueT> \fRm\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename\&.\&.\&. Ts> 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::variant< Ts\&.\&.\&. > & v, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a variant \\C V from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Read (S & s, std::vector< _valueT, _Alloc > & v, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Reads a vector<_valueT> \fRv\fP from \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, bool value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, const std::string & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, double val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, float val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, int16_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, int32_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, int64_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, int8_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, uint16_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, uint32_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, uint64_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::generic::stream_protocol::socket & s, uint8_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, bool value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, const std::string & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, double val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, float val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, int16_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, int32_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, int64_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, int8_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, uint16_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, uint32_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, uint64_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::ip::tcp::socket & s, uint8_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, bool value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, const std::string & value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, double val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, float val, boost::system::error_code & ec)\fR [static]\fP"

.PP
Writes \fRval\fP to \fRs\fP, in IEEE format (see RFC 1832 and/or ANSI/IEEE Standard 754-1985)\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, int16_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, int32_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, int64_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, int8_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, uint16_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, uint32_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, uint64_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "static bool Dwm::ASIO::Write (boost::asio::local::stream_protocol::socket & s, uint8_t value, boost::system::error_code & ec)\fR [static]\fP"

.PP
Write \fRvalue\fP to the given socket \fRs\fP\&. Returns true on success, false on failure\&. 
.SS "template<typename S , typename _valueT , size_t N> 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::array< _valueT, N > & a, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes an array<_valueT\&.N> \fRv\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::deque< _valueT, _Alloc > & d, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a deque<_valueT> \fRd\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::list< _valueT, _Alloc > & l, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a list<_valueT> \fRl\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::map< _keyT, _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a map<_keyT,_valueT> \fRm\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _keyT , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::multimap< _keyT, _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a multimap<_keyT,_valueT> \fRm\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::multiset< _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a multiset<_valueT> \fRm\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _firstT , typename _secondT > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::pair< _firstT, _secondT > & p, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a pair<_firstT,_secondT> to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Compare , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::set< _valueT, _Compare, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a set<_valueT> \fRm\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename\&.\&.\&. Args> 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::tuple< Args\&.\&.\&. > & t, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a tuple to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _keyT , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::unordered_map< _keyT, _valueT, _Hash, _Pred, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a unordered_map<_keyT,_valueT> \fRm\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Hash , typename _Pred , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::unordered_set< _valueT, _Hash, _Pred, _Alloc > & m, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a unordered_set<_valueT> \fRm\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename\&.\&.\&. Ts> 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::variant< Ts\&.\&.\&. > & v, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a variant \fRv\fP to \fRs\fP\&. Returns \fRtrue\fP on sucess, \fRfalse\fP on failure\&. 
.SS "template<typename S , typename _valueT , typename _Alloc > 
.br
requires IsSupportedASIOSocket<S>static bool Dwm::ASIO::Write (S & s, const std::vector< _valueT, _Alloc > & v, boost::system::error_code & ec)\fR [inline]\fP, \fR [static]\fP"

.PP
Writes a vector<_valueT> \fRv\fP to \fRs\fP\&. Returns \fRtrue\fP on success, \fRfalse\fP on failure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
