.TH "Dwm::CvsTag" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::CvsTag \- This class can be used to wrap a string containing CVS keyword name/value pairs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmCvsTag\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCvsTag\fP (const std::string &tagString)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "std::string \fBName\fP () const"
.br
.RI "Returns the value of the Name tag\&. "
.ti -1c
.RI "std::string \fBId\fP () const"
.br
.RI "Returns the value of the Id tag\&. "
.ti -1c
.RI "std::string \fBAuthor\fP () const"
.br
.RI "Returns the value of the Author tag\&. "
.ti -1c
.RI "std::string \fBHeader\fP () const"
.br
.RI "Returns the value of the Header tag\&. "
.ti -1c
.RI "std::string \fBDate\fP () const"
.br
.RI "Returns the value of the Date tag\&. "
.ti -1c
.RI "std::string \fBRCSfile\fP () const"
.br
.RI "Returns the value of the RCSfile tag\&. "
.ti -1c
.RI "std::string \fBRevision\fP () const"
.br
.RI "Returns the value of the Revision tag\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class can be used to wrap a string containing CVS keyword name/value pairs\&. 

The constructor accepts a string containing CVS keyword/value pairs\&. The other public members permit the retrieval of the value of the particular keyword\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
