.TH "Dwm::Assertions" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Assertions \- A container to hold all assertions\&. Note everything is static here\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmUnitAssert\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBFailed\fP (const std::string &filename, const std::string &function, int lineNumber, const std::string &test)"
.br
.RI "Adds a failed assertion\&. "
.ti -1c
.RI "static bool \fBPassed\fP (const std::string &filename, const std::string &function, int lineNumber, const std::string &test)"
.br
.RI "Adds a passed assertion\&. "
.ti -1c
.RI "static \fBAssertionCounter\fP \fBTotal\fP ()"
.br
.RI "Returns the total passed and failed counter\&. "
.ti -1c
.RI "static std::ostream & \fBPrint\fP (std::ostream &os, bool onlyFailed=false)"
.br
.RI "Prints to an ostream\&. "
.ti -1c
.RI "static int \fBPrintAndReturn\fP ()"
.br
.RI "Prints failed tests to cerr and successful test count to cout in a simple form that I use in unit test applications\&. "
.ti -1c
.RI "static std::ostream & \fBPrintJson\fP (std::ostream &os, bool onlyFailed=false)"
.br
.RI "Prints to an ostream in JSON format\&. "
.ti -1c
.RI "static std::ostream & \fBPrintXML\fP (std::ostream &os, bool onlyFailed=false)"
.br
.RI "Prints to an ostream in XML format\&. "
.in -1c
.SH "Detailed Description"
.PP 
A container to hold all assertions\&. Note everything is static here\&. 
.SH "Member Function Documentation"
.PP 
.SS "static bool Dwm::Assertions::Failed (const std::string & filename, const std::string & function, int lineNumber, const std::string & test)\fR [static]\fP"

.PP
Adds a failed assertion\&. Not called directly; \fBUnitAssert()\fP calls this member\&. Always returns false\&. 
.SS "static bool Dwm::Assertions::Passed (const std::string & filename, const std::string & function, int lineNumber, const std::string & test)\fR [static]\fP"

.PP
Adds a passed assertion\&. Not called directly; \fBUnitAssert()\fP calls this member\&. Always returns true\&. 
.SS "static std::ostream & Dwm::Assertions::Print (std::ostream & os, bool onlyFailed = \fRfalse\fP)\fR [static]\fP"

.PP
Prints to an ostream\&. If \fRonlyFailed\fP is true, prints only information for failed assertions\&. 
.SS "static int Dwm::Assertions::PrintAndReturn ()\fR [static]\fP"

.PP
Prints failed tests to cerr and successful test count to cout in a simple form that I use in unit test applications\&. Returns 0 if all unit tests passed, else returns 1\&. The return value can be used as the exit value of a unit test application to signal to the shell as to whether or not all unit tests passed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
