.TH "Dwm::IpAddress" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::IpAddress \- This class encapsulates an IP address\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmIpAddress\&.hh>\fP
.PP
Inherits \fBDwm::StreamIOCapable\fP, Dwm::FileIOCapable, \fBDwm::DescriptorIOCapable\fP, \fBDwm::StreamedLengthCapable\fP, \fBDwm::GZIOCapable\fP, and \fBDwm::BZ2IOCapable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIpAddress\fP (const \fBIpAddress\fP &addr)"
.br
.ti -1c
.RI "\fBIpAddress\fP & \fBoperator=\fP (const \fBIpAddress\fP &addr)"
.br
.ti -1c
.RI "\fBIpAddress\fP (const \fBIpv6Address\fP &addr)"
.br
.ti -1c
.RI "\fBIpAddress\fP (const \fBIpv4Address\fP &addr)"
.br
.ti -1c
.RI "\fBIpAddress\fP (const std::string &addr)"
.br
.ti -1c
.RI "int \fBFamily\fP () const"
.br
.ti -1c
.RI "template<typename T > const T * \fBAddr\fP () const"
.br
.ti -1c
.RI "\fBoperator std::string\fP () const"
.br
.RI "Returns a string representation\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBIpAddress\fP &addr) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBIpAddress\fP &addr) const"
.br
.ti -1c
.RI "uint64_t \fBStreamedLength\fP () const"
.br
.RI "Returns the number of bytes that would be written if we called one of the non-compressing \fBWrite()\fP members\&. "
.ti -1c
.RI "std::istream & \fBRead\fP (std::istream &is)"
.br
.RI "Reads from an istream\&. Returns the istream\&. "
.ti -1c
.RI "std::ostream & \fBWrite\fP (std::ostream &os) const"
.br
.RI "Writes to an ostream\&. Returns the ostream\&. "
.ti -1c
.RI "ssize_t \fBRead\fP (int fd)"
.br
.RI "Reads from a file descriptor\&. "
.ti -1c
.RI "ssize_t \fBWrite\fP (int fd) const"
.br
.RI "Writes to a file descriptor\&. "
.ti -1c
.RI "size_t \fBRead\fP (FILE *f)"
.br
.RI "Reads from a FILE pointer\&. Returns 1 on success, 0 on failure\&. "
.ti -1c
.RI "size_t \fBWrite\fP (FILE *f) const"
.br
.RI "Writes to a FILE pointer\&. Returns 1 on success, 0 on failure\&. "
.ti -1c
.RI "int \fBRead\fP (gzFile gzf)"
.br
.RI "Reads from a gzFile\&. "
.ti -1c
.RI "int \fBWrite\fP (gzFile gzf) const"
.br
.RI "Writes to a gzFile\&. "
.ti -1c
.RI "int \fBBZRead\fP (BZFILE *bzf)"
.br
.RI "Reads from a BZFILE pointer\&. "
.ti -1c
.RI "int \fBBZWrite\fP (BZFILE *bzf) const"
.br
.RI "Writes to a BZFILE pointer\&. "
.in -1c

Public Member Functions inherited from \fBDwm::StreamReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamReadable\fP ()"
.br
.RI "destructor "
.in -1c

Public Member Functions inherited from \fBDwm::StreamWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamWritable\fP ()"
.br
.RI "Destructor\&. "
.in -1c

Public Member Functions inherited from \fBDwm::DescriptorReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~DescriptorReadable\fP ()"
.br
.RI "destructor "
.in -1c

Public Member Functions inherited from \fBDwm::DescriptorWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~DescriptorWritable\fP ()"
.br
.RI "Destructor\&. "
.in -1c

Public Member Functions inherited from \fBDwm::GZReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~GZReadable\fP ()"
.br
.RI "destructor "
.in -1c

Public Member Functions inherited from \fBDwm::GZWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~GZWritable\fP ()"
.br
.RI "destructor "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBIpAddress\fP &addr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class encapsulates an IP address\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Dwm::IpAddress::BZRead (BZFILE * bzf)\fR [virtual]\fP"

.PP
Reads from a BZFILE pointer\&. Returns the number of bytes read (4 on success)\&. 
.PP
Implements \fBDwm::BZ2Readable\fP\&.
.SS "int Dwm::IpAddress::BZWrite (BZFILE * bzf) const\fR [virtual]\fP"

.PP
Writes to a BZFILE pointer\&. Returns the number of bytes written (4 on success)\&. 
.PP
Implements \fBDwm::BZ2Writable\fP\&.
.SS "size_t Dwm::IpAddress::Read (FILE * f)\fR [virtual]\fP"

.PP
Reads from a FILE pointer\&. Returns 1 on success, 0 on failure\&. 
.PP
Implements \fBDwm::FileReadable\fP\&.
.SS "int Dwm::IpAddress::Read (gzFile gzf)\fR [virtual]\fP"

.PP
Reads from a gzFile\&. Returns the number of bytes read (4 on success)\&. 
.PP
Implements \fBDwm::GZReadable\fP\&.
.SS "ssize_t Dwm::IpAddress::Read (int fd)\fR [virtual]\fP"

.PP
Reads from a file descriptor\&. Returns the number of bytes read (4 on success)\&. 
.PP
Implements \fBDwm::DescriptorReadable\fP\&.
.SS "std::istream & Dwm::IpAddress::Read (std::istream & is)\fR [virtual]\fP"

.PP
Reads from an istream\&. Returns the istream\&. 
.PP
Implements \fBDwm::StreamReadable\fP\&.
.SS "uint64_t Dwm::IpAddress::StreamedLength () const\fR [virtual]\fP"

.PP
Returns the number of bytes that would be written if we called one of the non-compressing \fBWrite()\fP members\&. 
.PP
Implements \fBDwm::StreamedLengthCapable\fP\&.
.SS "size_t Dwm::IpAddress::Write (FILE * f) const\fR [virtual]\fP"

.PP
Writes to a FILE pointer\&. Returns 1 on success, 0 on failure\&. 
.PP
Implements \fBDwm::FileWritable\fP\&.
.SS "int Dwm::IpAddress::Write (gzFile gzf) const\fR [virtual]\fP"

.PP
Writes to a gzFile\&. Returns the number of bytes written (4 on success)\&. 
.PP
Implements \fBDwm::GZWritable\fP\&.
.SS "ssize_t Dwm::IpAddress::Write (int fd) const\fR [virtual]\fP"

.PP
Writes to a file descriptor\&. Returns the number of bytes written (4 on success)\&. 
.PP
Implements \fBDwm::DescriptorWritable\fP\&.
.SS "std::ostream & Dwm::IpAddress::Write (std::ostream & os) const\fR [virtual]\fP"

.PP
Writes to an ostream\&. Returns the ostream\&. 
.PP
Implements \fBDwm::StreamWritable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
