.TH "Dwm::PathUtils" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::PathUtils \- This class just encapsulates miscellaneous utility functions for working with UNIX paths (files and directories)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmPathUtils\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsDirectory\fP (const std::string &path)"
.br
.RI "Returns true if \fRpath\fP is a directory\&. "
.ti -1c
.RI "static bool \fBHasSuffix\fP (const std::string &path, const std::string &suffix)"
.br
.RI "Returns true if \fRpath\fP is suffixed with \fRsuffix\fP\&. "
.ti -1c
.RI "static std::string \fBBasename\fP (const std::string &path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class just encapsulates miscellaneous utility functions for working with UNIX paths (files and directories)\&. 
.SH "Member Function Documentation"
.PP 
.SS "static bool Dwm::PathUtils::HasSuffix (const std::string & path, const std::string & suffix)\fR [static]\fP"

.PP
Returns true if \fRpath\fP is suffixed with \fRsuffix\fP\&. For example, HasSuffix('foo\&.cc','\&.cc') would return true\&. 
.SS "static bool Dwm::PathUtils::IsDirectory (const std::string & path)\fR [static]\fP"

.PP
Returns true if \fRpath\fP is a directory\&. Note that this will also return true if \fRpath\fP is a symbolic link pointing to a directory\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
