.TH "Dwm::Argument< T >" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Argument< T > \- Encapsulate a single argument\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmArguments\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgument\fP (const ValueType &v, const std::string &valueName='', const std::string &help='')"
.br
.ti -1c
.RI "const ValueType & \fBValue\fP () const"
.br
.ti -1c
.RI "const ValueType & \fBValue\fP (const ValueType &v)"
.br
.ti -1c
.RI "ValueType & \fBValue\fP ()"
.br
.ti -1c
.RI "const std::string & \fBValueName\fP () const"
.br
.ti -1c
.RI "const std::string & \fBValueName\fP (const std::string &valueName)"
.br
.ti -1c
.RI "const std::string & \fBHelp\fP () const"
.br
.ti -1c
.RI "const std::string & \fBHelp\fP (const std::string &help)"
.br
.ti -1c
.RI "const std::set< char > & \fBConflicts\fP () const"
.br
.ti -1c
.RI "const std::set< char > & \fBConflicts\fP (const std::set< char > &conflicts)"
.br
.ti -1c
.RI "std::string \fBUsageString\fP () const"
.br
.ti -1c
.RI "std::string \fBHelpText\fP () const"
.br
.ti -1c
.RI "\fBArgument\fP & \fBoperator=\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBoperator T\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr char \fBOptChar\fP ()"
.br
.ti -1c
.RI "static constexpr bool \fBRequired\fP ()"
.br
.ti -1c
.RI "static constexpr bool \fBNeedsValue\fP ()"
.br
.ti -1c
.RI "static std::string \fBIndentedText\fP (const std::string &s)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T \fB_value\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBArgument\fP< T > &arg)"
.br
.RI "ostream operator << for \fBArgument\fP instances\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Dwm::Argument< T >"Encapsulate a single argument\&. 

Simple class template for a command-line argument\&.
.PP
Pre-declare the \fBArgument\fP class template\&.
.PP
C is the character of the argument, ValueType is the type of the argument (bool for arguments that that don't take a value), Req must be true for required arguments\&.
.PP
This can be used directly, thought it typically is only used by \fBOptArgs\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
