.TH "Dwm::PackageInfo" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::PackageInfo \- Class with static members to get package name and version\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmPackageInfo\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const std::string & \fBName\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBVersion\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBBugReport\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBURL\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class with static members to get package name and version\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
