.TH "Dwm::Signal" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Signal \- This class encapsulates a signal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmSignal\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignal\fP (int sigNum)"
.br
.RI "Construct from a signal number (e\&.g\&. SIGHUP)\&. "
.ti -1c
.RI "\fBSignal\fP (const \fBSignal\fP &signal)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "bool \fBBlock\fP ()"
.br
.RI "Block the signal\&. "
.ti -1c
.RI "bool \fBUnblock\fP ()"
.br
.RI "Unblock the signal\&. "
.ti -1c
.RI "bool \fBIsBlocked\fP ()"
.br
.RI "Returns true if the signal is currently blocked\&. "
.ti -1c
.RI "bool \fBIsPending\fP ()"
.br
.RI "Returns true if the signal is currently pending\&. "
.ti -1c
.RI "void \fBWait\fP ()"
.br
.RI "Waits for the delivery of the signal to the calling thread\&. "
.ti -1c
.RI "int \fBPushHandler\fP (void(*handler)(int))"
.br
.RI "Pushes a signal onto the top of a stack of signal handlers for the signal\&. "
.ti -1c
.RI "int \fBPopHandler\fP ()"
.br
.RI "Pops the top signal handler off of the stack of signal handlers\&. "
.ti -1c
.RI "const std::string & \fBName\fP () const"
.br
.RI "Returns a string representation of the signal ('e\&.g\&. 'SIGHUP")\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_sigNum\fP"
.br
.ti -1c
.RI "std::deque< void(*)(int)> \fB_handlers\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const std::map< int, std::string, std::less< int > > \fB_names\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class encapsulates a signal\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Dwm::Signal::PushHandler (void(* handler )(int))"

.PP
Pushes a signal onto the top of a stack of signal handlers for the signal\&. The handler on the top of the stack is the one which will be called on reception of the signal\&. 
.SS "void Dwm::Signal::Wait ()"

.PP
Waits for the delivery of the signal to the calling thread\&. See the sigwait() manpage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
