.TH "Dwm::IsSupportedASIOSocket" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::IsSupportedASIOSocket \- Concept for the types of ASIO sockets we can utilize\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmASIO\&.hh>\fP
.SH "Concept definition"
.PP 

.nf
template<typename S>
concept Dwm::IsSupportedASIOSocket = 
  std::is_same_v<S,boost::asio::ip::tcp::socket>
    || std::is_same_v<S,boost::asio::local::stream_protocol::socket>
    || std::is_same_v<S,boost::asio::generic::stream_protocol::socket>
.PP
.fi
.SH "Detailed Description"
.PP 
Concept for the types of ASIO sockets we can utilize\&. 

Originally I only used ASIO for TCP sockets, but later I had use cases for UNIX domain sockets\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
