.TH "Dwm::FFIVar< T, typename std::enable_if< std::is_floating_point< T >::value >::type >" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::FFIVar< T, typename std::enable_if< std::is_floating_point< T >::value >::type > \- Specialization for floating point types\&. No bitwise operators\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmFFIVar\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFFIVar\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fB~FFIVar\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBFFIVar\fP (const \fBFFIVar\fP &v)=default"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBFFIVar\fP (const T &t)"
.br
.RI "Construct from a reference to a \fRT\fP\&. "
.ti -1c
.RI "\fBFFIVar\fP (\fBFFIVar\fP &&v)=default"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "\fBFFIVar\fP (T &&t)"
.br
.RI "Construct from an rvalue reference to a \fRT\fP\&. "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator=\fP (const \fBFFIVar\fP &v)=default"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator=\fP (const T &t)"
.br
.RI "Assign from a \fRT\fP\&. "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator=\fP (\fBFFIVar\fP &&)=default"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator=\fP (T &&t)"
.br
.RI "Move assign from an rvalue reference to a \fRT\fP\&. "
.ti -1c
.RI "\fBoperator T\fP () const"
.br
.RI "Conversion to T operator\&. "
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBFFIVar\fP &v) const"
.br
.RI "Less than or equal operator\&. "
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBFFIVar\fP &v) const"
.br
.RI "Greater than or equal operator\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBFFIVar\fP &v) const"
.br
.RI "Less-than operator\&. "
.ti -1c
.RI "bool \fBoperator>\fP (const \fBFFIVar\fP &v) const"
.br
.RI "Greater-than operator\&. "
.ti -1c
.RI "template<typename IT > bool \fBoperator==\fP (const IT &it) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFFIVar\fP &v) const"
.br
.RI "Equality operator\&. "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator+=\fP (const \fBFFIVar\fP &v)"
.br
.RI "compound add and assignment operator "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator\-=\fP (const \fBFFIVar\fP &v)"
.br
.RI "compound subtract and assignment operator "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator*=\fP (const \fBFFIVar\fP &v)"
.br
.RI "compound multiply and assignment operator "
.ti -1c
.RI "\fBFFIVar\fP & \fBoperator/=\fP (const \fBFFIVar\fP &v)"
.br
.RI "compound divide and assignment operator "
.ti -1c
.RI "bool \fBIsFFI\fP () const"
.br
.RI "Returns true if object appears to be free from interference\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Dwm::FFIVar< T, typename std::enable_if< std::is_floating_point< T >::value >::type >"Specialization for floating point types\&. No bitwise operators\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
