.TH "Dwm::TermioFlagInfo_t" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::TermioFlagInfo_t \- Holds termios flag values and names\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmTermios\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tcflag_t \fBflag\fP"
.br
.ti -1c
.RI "tcflag_t \fBmask\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBlongName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds termios flag values and names\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
