.TH "Dwm::MacAddress" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::MacAddress \- Encapsulates a 6-byte MAC address\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmMacAddress\&.hh>\fP
.PP
Inherits \fBDwm::DescriptorIOCapable\fP, Dwm::FileIOCapable, \fBDwm::StreamIOCapable\fP, \fBDwm::StreamedLengthCapable\fP, \fBDwm::GZIOCapable\fP, and \fBDwm::BZ2IOCapable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMacAddress\fP ()"
.br
.RI "Constructor\&. Sets the address to 00:00:00:00:00:00\&. "
.ti -1c
.RI "\fBMacAddress\fP (const std::string &s)"
.br
.RI "Construct from a string of the form xx:xx:xx:xx:xx:xx\&. "
.ti -1c
.RI "\fBMacAddress\fP (const \fBMacAddress\fP &addr)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBMacAddress\fP & \fBoperator=\fP (const \fBMacAddress\fP &addr)"
.br
.RI "operator = "
.ti -1c
.RI "\fBoperator std::string\fP () const"
.br
.RI "Returns a string representation of the MAC address\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMacAddress\fP &addr) const"
.br
.RI "operator == "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBMacAddress\fP &addr) const"
.br
.RI "operator < "
.ti -1c
.RI "std::istream & \fBRead\fP (std::istream &is) override"
.br
.RI "Reads the MAC address from an istream\&. Returns the istream\&. "
.ti -1c
.RI "std::ostream & \fBWrite\fP (std::ostream &os) const override"
.br
.RI "Writes the MAC address to an ostream\&. Returns the ostream\&. "
.ti -1c
.RI "ssize_t \fBRead\fP (int fd) override"
.br
.RI "Reads the MAC address from a file descriptor\&. "
.ti -1c
.RI "ssize_t \fBWrite\fP (int fd) const override"
.br
.RI "Writes the MAC address to a file descriptor\&. "
.ti -1c
.RI "size_t \fBRead\fP (FILE *f) override"
.br
.RI "Reads the MAC address from a FILE\&. "
.ti -1c
.RI "size_t \fBWrite\fP (FILE *f) const override"
.br
.RI "Writes the MAC address to a FILE\&. "
.ti -1c
.RI "int \fBRead\fP (gzFile gzf) override"
.br
.RI "Reads the MAC address from a gzFile\&. "
.ti -1c
.RI "int \fBWrite\fP (gzFile gzf) const override"
.br
.RI "Writes the MAC address to a gzFile\&. "
.ti -1c
.RI "int \fBBZRead\fP (BZFILE *bzf) override"
.br
.RI "Reads the MAC address from a BZFILE\&. "
.ti -1c
.RI "int \fBBZWrite\fP (BZFILE *bzf) const override"
.br
.RI "Writes the MAC address to a BZFILE\&. "
.ti -1c
.RI "uint64_t \fBStreamedLength\fP () const override"
.br
.RI "Returns the number of bytes that should be written if we call one of the \fBWrite()\fP members\&. "
.in -1c

Public Member Functions inherited from \fBDwm::DescriptorReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~DescriptorReadable\fP ()"
.br
.RI "destructor "
.in -1c

Public Member Functions inherited from \fBDwm::DescriptorWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~DescriptorWritable\fP ()"
.br
.RI "Destructor\&. "
.in -1c

Public Member Functions inherited from \fBDwm::StreamReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamReadable\fP ()"
.br
.RI "destructor "
.in -1c

Public Member Functions inherited from \fBDwm::StreamWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamWritable\fP ()"
.br
.RI "Destructor\&. "
.in -1c

Public Member Functions inherited from \fBDwm::GZReadable\fP
.in +1c
.ti -1c
.RI "virtual \fB~GZReadable\fP ()"
.br
.RI "destructor "
.in -1c

Public Member Functions inherited from \fBDwm::GZWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~GZWritable\fP ()"
.br
.RI "destructor "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fB_addr\fP [6]"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBMacAddress\fP &addr)"
.br
.RI "Prints to an ostream in 'xx:xx:xx:xx:xx:xx' format\&. "
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBMacAddress\fP &addr)"
.br
.RI "Reads from an istream in 'xx:xx:xx:xx:xx:xx' format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Encapsulates a 6-byte MAC address\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Dwm::MacAddress::BZRead (BZFILE * bzf)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reads the MAC address from a BZFILE\&. Returns the number of bytes read on success (should be 6), -1 on failure\&. 
.PP
Implements \fBDwm::BZ2Readable\fP\&.
.SS "int Dwm::MacAddress::BZWrite (BZFILE * bzf) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Writes the MAC address to a BZFILE\&. Returns the number of bytes written on success (should be 6), -1 on failure\&. 
.PP
Implements \fBDwm::BZ2Writable\fP\&.
.SS "size_t Dwm::MacAddress::Read (FILE * f)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reads the MAC address from a FILE\&. Returns 1 on success, 0 on failure\&. 
.PP
Implements \fBDwm::FileReadable\fP\&.
.SS "int Dwm::MacAddress::Read (gzFile gzf)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reads the MAC address from a gzFile\&. Returns the number of bytes read on success (should be 6), -1 on failure\&. 
.PP
Implements \fBDwm::GZReadable\fP\&.
.SS "ssize_t Dwm::MacAddress::Read (int fd)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reads the MAC address from a file descriptor\&. Returns the number of bytes read on success (should be 6), -1 on failure\&. 
.PP
Implements \fBDwm::DescriptorReadable\fP\&.
.SS "std::istream & Dwm::MacAddress::Read (std::istream & is)\fR [override]\fP, \fR [virtual]\fP"

.PP
Reads the MAC address from an istream\&. Returns the istream\&. 
.PP
Implements \fBDwm::StreamReadable\fP\&.
.SS "uint64_t Dwm::MacAddress::StreamedLength () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Returns the number of bytes that should be written if we call one of the \fBWrite()\fP members\&. Should always return 6\&. 
.PP
Implements \fBDwm::StreamedLengthCapable\fP\&.
.SS "size_t Dwm::MacAddress::Write (FILE * f) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Writes the MAC address to a FILE\&. Returns 1 on success, 0 on failure\&. 
.PP
Implements \fBDwm::FileWritable\fP\&.
.SS "int Dwm::MacAddress::Write (gzFile gzf) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Writes the MAC address to a gzFile\&. Returns the number of bytes written on success (should be 6), -1 on failure\&. 
.PP
Implements \fBDwm::GZWritable\fP\&.
.SS "ssize_t Dwm::MacAddress::Write (int fd) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Writes the MAC address to a file descriptor\&. Returns the number of bytes written on success (should be 6), -1 on failure\&. 
.PP
Implements \fBDwm::DescriptorWritable\fP\&.
.SS "std::ostream & Dwm::MacAddress::Write (std::ostream & os) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Writes the MAC address to an ostream\&. Returns the ostream\&. 
.PP
Implements \fBDwm::StreamWritable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
