.TH "Dwm::Writable" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Writable \- This class defines an interface for classes that can write their contents to an ostream, file descriptor or FILE pointer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmWritable\&.hh>\fP
.PP
Inherits \fBDwm::DescriptorWritable\fP, \fBDwm::FileWritable\fP, and \fBDwm::StreamWritable\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBDwm::DescriptorWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~DescriptorWritable\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual ssize_t \fBWrite\fP (int fd) const =0"
.br
.RI "Write to a file descriptor\&. "
.in -1c

Public Member Functions inherited from \fBDwm::FileWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~FileWritable\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual size_t \fBWrite\fP (FILE *f) const =0"
.br
.RI "Write to a FILE pointer\&. "
.in -1c

Public Member Functions inherited from \fBDwm::StreamWritable\fP
.in +1c
.ti -1c
.RI "virtual \fB~StreamWritable\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual std::ostream & \fBWrite\fP (std::ostream &os) const =0"
.br
.RI "Write to an ostream\&. Return the ostream\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class defines an interface for classes that can write their contents to an ostream, file descriptor or FILE pointer\&. 

Note that this class is deprecated as of libDwm-0\&.8\&.0, and is now just a grouping of \fBDescriptorWritable\fP, \fBFileWritable\fP and \fBStreamWritable\fP\&. The older version of this class also included a StreamedLength() pure virtual member\&. To get that interface, you now need to add \fBStreamedLengthCapable\fP to any derived class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
