.TH "Dwm::StringConverter" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::StringConverter \- Encapsulates conversion from a string to another type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmStringConverter\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > bool \fBoperator()\fP (const std::string &s, T &target) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Encapsulates conversion from a string to another type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
