.TH "Dwm::Password" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::Password \- Encapsulates an /etc/passwd entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmPassword\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPassword\fP (const std::string &userName)"
.br
.RI "Construct from a user name\&. "
.ti -1c
.RI "\fBPassword\fP (uid_t userId)"
.br
.RI "Construct from a user ID\&. "
.ti -1c
.RI "void \fBSet\fP (const struct passwd &passwdStruct)"
.br
.RI "Use the contents of \fRpasswdStruct\fP to fill all of our members\&. "
.ti -1c
.RI "const std::string & \fBUserName\fP () const"
.br
.RI "Returns the user name\&. "
.ti -1c
.RI "const std::string & \fBEncryptedPassword\fP () const"
.br
.RI "Returns the user password\&. "
.ti -1c
.RI "uid_t \fBUserId\fP () const"
.br
.RI "Returns the user ID\&. "
.ti -1c
.RI "gid_t \fBGroupId\fP () const"
.br
.RI "Returns the group ID\&. "
.ti -1c
.RI "const std::string & \fBGecos\fP () const"
.br
.RI "Returns the gecos\&. "
.ti -1c
.RI "const std::string & \fBHomeDirectory\fP () const"
.br
.RI "Returns the home directory\&. "
.ti -1c
.RI "const std::string & \fBShell\fP () const"
.br
.RI "Returns the shell\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBPassword\fP &password)"
.br
.RI "Prints to an ostream in /etc/passwd format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Encapsulates an /etc/passwd entry\&. 

The main reason for this class: some operating systems don't provide threadsafe versions of getpwuid() and getpwnam()\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
