.TH "Dwm::BZ2IOCapable" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dwm::BZ2IOCapable \- Interface for classes with \fBBZ2IO\fP read and write capabilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DwmBZ2IOCapable\&.hh>\fP
.PP
Inherits \fBDwm::BZ2Readable\fP, and \fBDwm::BZ2Writable\fP\&.
.PP
Inherited by \fBDwm::IpAddress\fP, Dwm::IpPrefix, \fBDwm::Ipv4Address\fP, \fBDwm::Ipv4PacketHeader\fP, \fBDwm::Ipv4Prefix\fP, \fBDwm::Ipv4Routes< _valueT >\fP, \fBDwm::Ipv4TcpHeader\fP, \fBDwm::Ipv4TcpPacket\fP, \fBDwm::Ipv4UdpHeader\fP, \fBDwm::Ipv4UdpPacket\fP, \fBDwm::Ipv6AddrMap< T, Hash >\fP, \fBDwm::Ipv6Address\fP, \fBDwm::Ipv6Prefix\fP, \fBDwm::Ipv6PrefixMap< T, Hash >\fP, \fBDwm::MacAddress\fP, \fBDwm::MplsLabel\fP, \fBDwm::MplsLabelStack\fP, Dwm::ProcessInfo, \fBDwm::TimeInterval\fP, \fBDwm::TimeInterval64\fP, \fBDwm::TimeValue\fP, and \fBDwm::TimeValue64\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBDwm::BZ2Readable\fP
.in +1c
.ti -1c
.RI "virtual int \fBBZRead\fP (BZFILE *bzf)=0"
.br
.RI "Read from a BZFILE pointer\&. "
.in -1c

Public Member Functions inherited from \fBDwm::BZ2Writable\fP
.in +1c
.ti -1c
.RI "virtual int \fBBZWrite\fP (BZFILE *bzf) const =0"
.br
.RI "Write to a BZFILE pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for classes with \fBBZ2IO\fP read and write capabilities\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
