.TH "DwmASIOCapable.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmASIOCapable.hh \- \fBDwm::ASIOReadable\fP, \fBDwm::ASIOWritable\fP, \fBDwm::ASIOCapable\fP interface declarations\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <boost/asio\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::ASIOReadable\fP"
.br
.RI "Interface for classes that wish to be readable via \fBDwm::ASIO\fP\&. "
.ti -1c
.RI "class \fBDwm::ASIOWritable\fP"
.br
.RI "Interface for classes that wish to be writable via \fBDwm::ASIO\fP\&. "
.ti -1c
.RI "class \fBDwm::ASIOCapable\fP"
.br
.RI "Interface for classes that can read/write their contents from/to a boost::asio::ip::tcp::socket\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::ASIOReadable\fP, \fBDwm::ASIOWritable\fP, \fBDwm::ASIOCapable\fP interface declarations\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
