.TH "DwmArgumentIO.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmArgumentIO.hh \- iostream helpers for Argument values  

.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <set>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'DwmTupleHelpers\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > std::ostream & \fBDwm::ArgumentIO::operator<<\fP (std::ostream &os, const std::vector< T > &t)"
.br
.ti -1c
.RI "template<class\&.\&.\&. Ts> std::ostream & \fBDwm::ArgumentIO::operator<<\fP (std::ostream &os, const std::tuple< Ts\&.\&.\&. > &t)"
.br
.ti -1c
.RI "template<class T > std::ostream & \fBDwm::ArgumentIO::operator<<\fP (std::ostream &os, const std::set< T > &s)"
.br
.ti -1c
.RI "template<class T1 , class T2 > std::ostream & \fBDwm::ArgumentIO::operator<<\fP (std::ostream &os, const std::pair< T1, T2 > &t)"
.br
.ti -1c
.RI "template<class T , size_t N> std::ostream & \fBDwm::ArgumentIO::operator<<\fP (std::ostream &os, const std::array< T, N > &t)"
.br
.ti -1c
.RI "template<class T > std::istream & \fBDwm::ArgumentIO::operator>>\fP (std::istream &is, std::vector< T > &v)"
.br
.ti -1c
.RI "template<class\&.\&.\&. Ts> std::istream & \fBDwm::ArgumentIO::operator>>\fP (std::istream &is, std::tuple< Ts\&.\&.\&. > &t)"
.br
.ti -1c
.RI "std::istream & \fBDwm::ArgumentIO::operator>>\fP (std::istream &is, std::string &s)"
.br
.ti -1c
.RI "template<class T > std::istream & \fBDwm::ArgumentIO::operator>>\fP (std::istream &is, std::set< T > &t)"
.br
.ti -1c
.RI "template<class T1 , class T2 > std::istream & \fBDwm::ArgumentIO::operator>>\fP (std::istream &is, std::pair< T1, T2 > &t)"
.br
.ti -1c
.RI "template<class T , size_t N> std::istream & \fBDwm::ArgumentIO::operator>>\fP (std::istream &is, std::array< T, N > &a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
iostream helpers for Argument values 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
