.TH "DwmBZ2IOCapable.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmBZ2IOCapable.hh \- \fBDwm::BZ2Readable\fP, \fBDwm::BZ2Writable\fP and \fBDwm::BZ2IOCapable\fP pure virtual interface declarations\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <bzlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::BZ2Readable\fP"
.br
.RI "This class is a pure virtual class, defining an interface for classes that can read their contents from a BZFILE pointer\&. "
.ti -1c
.RI "class \fBDwm::BZ2Writable\fP"
.br
.RI "This class is a pure virtual class, defining an interface for classes that can write their contents to a BZFILE pointer\&. "
.ti -1c
.RI "class \fBDwm::BZ2IOCapable\fP"
.br
.RI "Interface for classes with \fBBZ2IO\fP read and write capabilities\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::BZ2Readable\fP, \fBDwm::BZ2Writable\fP and \fBDwm::BZ2IOCapable\fP pure virtual interface declarations\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
