.TH "DwmCvsTag.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmCvsTag.hh \- \fBDwm::CvsTag\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::CvsTag\fP"
.br
.RI "This class can be used to wrap a string containing CVS keyword name/value pairs\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::CvsTag\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
