.TH "DwmConcurrentQueue.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmConcurrentQueue.hh \- \fBDwm::Thread::ConcurrentQueue\fP class template definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <unistd\&.h>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Thread::ConcurrentQueue< T >\fP"
.br
.RI "Concurrent queue template\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Thread::ConcurrentQueue\fP class template definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
