.TH "DwmDataLog.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmDataLog.hh \- \fBDwm::DataLog\fP and \fBDwm::DataLog::Entry\fP class templates\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cassert>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <iomanip>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'DwmIOUtils\&.hh'\fP
.br
\fR#include 'DwmStreamIO\&.hh'\fP
.br
\fR#include 'DwmSysLogger\&.hh'\fP
.br
\fR#include 'DwmTimeValue\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::DataLog< T >\fP"
.br
.RI "Simple class template for data logging\&. "
.ti -1c
.RI "class \fBDwm::DataLog< T >::Entry\fP"
.br
.RI "Encapsulates a single data log entry\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::DataLog\fP and \fBDwm::DataLog::Entry\fP class templates\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
