.TH "DwmDateTime.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmDateTime.hh \- \fBDwm::DateTime\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <inttypes\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'DwmTimeValue\&.hh'\fP
.br
\fR#include 'DwmTimeValue64\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::DateTime\fP"
.br
.RI "This class just encapsulates a struct tm and some of the typical functionality for dealing with date and time\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::DateTime\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
