.TH "DwmDescriptor.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmDescriptor.hh \- \fBDwm::Descriptor\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/time\&.h>\fP
.br
\fR#include <sys/uio\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Descriptor\fP"
.br
.RI "This class encapsulates UNIX file and socket descriptors\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Descriptor\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
