.TH "DwmDaemonUtils.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmDaemonUtils.hh \- \fBDwm::DaemonUtils\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::DaemonUtils\fP"
.br
.RI "Tiny collection of utilities for daemon processes\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::DaemonUtils\fP class definition\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
