.TH "DwmFileIOCapable.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmFileIOCapable.hh \- Dwm::FileIOCapable pure virtual class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::FileReadable\fP"
.br
.RI "This class defines an interface for classes that can read their contents from a FILE pointer\&. "
.ti -1c
.RI "class \fBDwm::FileWritable\fP"
.br
.RI "This class defines an interface for classes that can write their contents to a FILE pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Dwm::FileIOCapable pure virtual class declaration\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
