.TH "DwmFileRoller.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmFileRoller.hh \- \fBDwm::FileRoller\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cstdio>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <set>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::FileRoller\fP"
.br
.RI "This class can be used to roll over files such as log files\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::FileRoller\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
