.TH "DwmFileIO.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmFileIO.hh \- \fBDwm::FileIO\fP class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <list>\fP
.br
\fR#include <map>\fP
.br
\fR#include <set>\fP
.br
\fR#include <string>\fP
.br
\fR#include <tuple>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'DwmPortability\&.hh'\fP
.br
\fR#include 'DwmFileIOCapable\&.hh'\fP
.br
\fR#include 'DwmVariantFromIndex\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::FileIO\fP"
.br
.RI "This class contains a collection of static functions for reading and writing simple types, in network byte order (MSB first)\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::FileIO\fP class declaration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
