.TH "DwmFileLogger.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmFileLogger.hh \- \fBDwm::FileLogger\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <inttypes\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <syslog\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::FileLogger\fP"
.br
.RI "This class encapsulates syslog-like logging, but uses files instead of the syslog facility\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::FileLogger\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
