.TH "DwmGZIOCapable.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmGZIOCapable.hh \- \fBDwm::GZReadable\fP, \fBDwm::GZWritable\fP and \fBDwm::GZIOCapable\fP pure virtual class declarations\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <zlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::GZReadable\fP"
.br
.RI "This class is a pure virtual class, defining an interface for classes that can read their contents from a gzFile\&. "
.ti -1c
.RI "class \fBDwm::GZWritable\fP"
.br
.RI "This class is a pure virtual class, defining an interface for classes that can write their contents to a gzFile\&. "
.ti -1c
.RI "class \fBDwm::GZIOCapable\fP"
.br
.RI "Interface for classes with \fBGZIO\fP read and write capabilities\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::GZReadable\fP, \fBDwm::GZWritable\fP and \fBDwm::GZIOCapable\fP pure virtual class declarations\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
