.TH "DwmIpv4Routes.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmIpv4Routes.hh \- \fBDwm::Ipv4Routes\fP class template definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assert\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <future>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include 'DwmPortability\&.hh'\fP
.br
\fR#include 'DwmBZ2IO\&.hh'\fP
.br
\fR#include 'DwmDescriptorIO\&.hh'\fP
.br
\fR#include 'DwmFileIO\&.hh'\fP
.br
\fR#include 'DwmGZIO\&.hh'\fP
.br
\fR#include 'DwmIOUtils\&.hh'\fP
.br
\fR#include 'DwmStreamIO\&.hh'\fP
.br
\fR#include 'DwmIpv4Prefix\&.hh'\fP
.br
\fR#include 'DwmOperators\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Ipv4Routes< _valueT >\fP"
.br
.RI "This template class provides an associative container keyed by IPv4 addresses, with longest-match searching\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Ipv4Routes\fP class template definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
