.TH "DwmIpv4PacketHeader.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmIpv4PacketHeader.hh \- \fBDwm::Ipv4PacketHeader\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <netinet/in_systm\&.h>\fP
.br
\fR#include <netinet/in\&.h>\fP
.br
\fR#include <netinet/ip\&.h>\fP
.br
\fR#include 'DwmDescriptorIOCapable\&.hh'\fP
.br
\fR#include 'DwmFileIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamedLengthCapable\&.hh'\fP
.br
\fR#include 'DwmBZ2IOCapable\&.hh'\fP
.br
\fR#include 'DwmGZIOCapable\&.hh'\fP
.br
\fR#include 'DwmIpv4Address\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Ipv4PacketHeader\fP"
.br
.RI "Encapsulates an IPv4 packet header\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Ipv4PacketHeader\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
