.TH "DwmIpv4Utils.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmIpv4Utils.hh \- Miscellaneous IPv4 utilities\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <inttypes\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBDwm::Ipv4Utils::Sum\fP (const uint8_t *ptr, uint16_t len)"
.br
.RI "Compute the IP sum (part of checksum computation) of the memory at \fRptr\fP of length \fRlen\fP\&. "
.ti -1c
.RI "void \fBDwm::Ipv4Utils::AddCarries\fP (uint32_t &sum)"
.br
.RI "Part of IP checksum computation\&.\&.\&. add the carries and do the 1's complement\&. "
.in -1c
.SH "Detailed Description"
.PP 
Miscellaneous IPv4 utilities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
