.TH "DwmIpv4IcmpTimeExceeded.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmIpv4IcmpTimeExceeded.hh \- \fBDwm::Ipv4IcmpTimeExceeded\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <inttypes\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'DwmIpv4PacketHeader\&.hh'\fP
.br
\fR#include 'DwmIpv4IcmpMessage\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Ipv4IcmpTimeExceeded\fP"
.br
.RI "Encapsulates an ICMP source quench message\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Ipv4IcmpTimeExceeded\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
