.TH "DwmIO.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmIO.hh \- \fBDwm::IO\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'DwmDescriptorIO\&.hh'\fP
.br
\fR#include 'DwmFileIO\&.hh'\fP
.br
\fR#include 'DwmStreamIO\&.hh'\fP
.br
\fR#include 'DwmIOUtils\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::IO\fP"
.br
.RI "This class is now just a wrapper for \fBDescriptorIO\fP, \fBFileIO\fP, \fBStreamIO\fP and \fBIOUtils\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::IO\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
