.TH "DwmIpPrefix.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmIpPrefix.hh \- Dwm::IpPrefix class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <inttypes\&.h>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <variant>\fP
.br
\fR#include 'DwmIpAddress\&.hh'\fP
.br
\fR#include 'DwmIpv4Prefix\&.hh'\fP
.br
\fR#include 'DwmIpv6Prefix\&.hh'\fP
.br

.SH "Detailed Description"
.PP 
Dwm::IpPrefix class declaration\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
