.TH "DwmLocalInterfaces.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmLocalInterfaces.hh \- \fBDwm::LocalInterfaceAlias\fP, \fBDwm::LocalInterface\fP and \fBDwm::GetLocalInterfaces()\fP definitions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <netinet/in\&.h>\fP
.br
\fR#include <arpa/inet\&.h>\fP
.br
\fR#include <set>\fP
.br
\fR#include <string>\fP
.br
\fR#include <map>\fP
.br
\fR#include 'DwmIpv4Address\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::LocalInterfaceAlias\fP"
.br
.RI "Holds an interface alias, which is just IP address and netmask\&. "
.ti -1c
.RI "class \fBDwm::LocalInterface\fP"
.br
.RI "Simple class to hold the name and IPv4 address of a local interface\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBDwm::GetLocalInterfaces\fP (std::map< std::string, \fBLocalInterface\fP > &interfaces)"
.br
.RI "Fetches local interfaces with IP addresses into \fRinterfaces\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::LocalInterfaceAlias\fP, \fBDwm::LocalInterface\fP and \fBDwm::GetLocalInterfaces()\fP definitions\&. 


.SH "Function Documentation"
.PP 
.SS "bool Dwm::GetLocalInterfaces (std::map< std::string, \fBLocalInterface\fP > & interfaces)"

.PP
Fetches local interfaces with IP addresses into \fRinterfaces\fP\&. Returns true on success (1 or more interfaces found)\&. This \fIshould\fP work on OpenBSD, FreeBSD and Linux\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
