.TH "DwmLoadBalancer.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmLoadBalancer.hh \- \fBDwm::LoadBalancer\fP class template definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <algorithm>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'DwmThreadQueue\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::LoadBalancer< ItemT >\fP"
.br
.RI "A simple load balancer class template which balances work across \fBWorker\fP objects that each run in their own thread\&. "
.ti -1c
.RI "class \fBDwm::LoadBalancer< ItemT >::Worker\fP"
.br
.RI "\fBWorker\fP class for \fBLoadBalancer\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::LoadBalancer\fP class template definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
