.TH "DwmMplsLabelStack.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmMplsLabelStack.hh \- \fBDwm::MplsLabelStack\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include 'DwmMplsLabel\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::MplsLabelStack\fP"
.br
.RI "Encapsulates an MPLS label stack\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::MplsLabelStack\fP class definition\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
