.TH "DwmOptArgs.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmOptArgs.hh \- \fBDwm::Argument\fP, \fBDwm::OptArg\fP and \fBDwm::OptArgs\fP definitions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <map>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'DwmStringUtils\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Argument< T >\fP"
.br
.RI "Encapsulate a single argument\&. "
.ti -1c
.RI "class \fBDwm::OptArg\fP"
.br
.RI "Encapsulates a command line option and its argument (if it takes an argument)\&. "
.ti -1c
.RI "class \fBDwm::OptArgs\fP"
.br
.RI "Class to encapsulate command line options and parse them\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::ostream & \fBDwm::operator<<\fP (std::ostream &os, const \fBArgument\fP< T > &arg)"
.br
.RI "ostream operator << for \fBArgument\fP instances\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Argument\fP, \fBDwm::OptArg\fP and \fBDwm::OptArgs\fP definitions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
