.TH "DwmProcessTree.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmProcessTree.hh \- \fBDwm::ProcessTree\fP class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'DwmProcessTable\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::ProcessTree\fP"
.br
.RI "Encapsulates a process tree, i\&.e\&. a process and its descendants\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBDwm::ToJson\fP (const \fBProcessTree\fP &processTree, nlohmann::json &json)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::ProcessTree\fP class declaration\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
