.TH "DwmProcessTable.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmProcessTable.hh \- \fBDwm::ProcessTable\fP typedef and utility function prototypes\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <map>\fP
.br
\fR#include 'DwmProcessInfo\&.hh'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< pid_t, Dwm::ProcessInfo > \fBDwm::ProcessTable\fP"
.br
.RI "We represent a process table as a map of Dwm::Process keyed by process ID\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBDwm::GetProcessTable\fP (\fBProcessTable\fP &processTable)"
.br
.RI "Fetches the current process table\&. Returns true on success\&. "
.ti -1c
.RI "bool \fBDwm::GetProcessInfo\fP (pid_t pid, ProcessInfo &processInfo)"
.br
.ti -1c
.RI "bool \fBDwm::ToJson\fP (const \fBProcessTable\fP &processTable, nlohmann::json &json)"
.br
.ti -1c
.RI "nlohmann::json \fBDwm::ToJson\fP (const \fBProcessTable\fP &processTable)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBDwm::ProcessTable\fP &pt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::ProcessTable\fP typedef and utility function prototypes\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
