.TH "DwmPortability.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmPortability.hh \- A configure target for dealing with OS differences\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <CoreFoundation/CFByteOrder\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_CFBYTE_ORDER_H\fP   1"
.br
.ti -1c
.RI "#define \fBbe64toh\fP(x)   OSSwapBigToHostInt64((x))"
.br
.ti -1c
.RI "#define \fBhtobe64\fP(x)   OSSwapHostToBigInt64((x))"
.br
.ti -1c
.RI "#define \fBbe32toh\fP(x)   OSSwapBigToHostInt32(x)"
.br
.ti -1c
.RI "#define \fBhtobe32\fP(x)   OSSwapHostToBigInt32(x)"
.br
.ti -1c
.RI "#define \fBbe16toh\fP(x)   OSSwapBigToHostInt16(x)"
.br
.ti -1c
.RI "#define \fBhtobe16\fP(x)   OSSwapHostToBigInt16(x)"
.br
.ti -1c
.RI "#define \fBHAVE_CPP11\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CPP17\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CPP20\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GPLUSPLUS_VERSION\fP(MAJOR,  MINOR)     (__GNUC__ > (MAJOR) || (__GNUC__ == (MAJOR) && __GNUC_MINOR__ >= (MINOR)))"
.br
.ti -1c
.RI "#define \fBDWM_HAVE_STD_FORMAT\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
A configure target for dealing with OS differences\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
