.TH "DwmPatricia.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmPatricia.hh \- NOT YET DOCUMENTED\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'DwmIOUtils\&.hh'\fP
.br
\fR#include 'DwmDescriptorIO\&.hh'\fP
.br
\fR#include 'DwmStreamIO\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::PatriciaNode< KeyType, ValueType >\fP"
.br
.RI "A node in a \fBPatricia\fP trie\&. "
.ti -1c
.RI "class \fBDwm::Patricia< KeyType, ValueType, KeyEqual >\fP"
.br
.RI "Pre-declare the \fBPatricia\fP class template\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename KeyType > int \fBDwm::GetBit\fP (const KeyType &key, int bit)"
.br
.ti -1c
.RI "template<typename KeyType > int \fBDwm::BitFirstDifferent\fP (const KeyType &key1, const KeyType &key2)"
.br
.ti -1c
.RI "template<typename KeyType > bool \fBDwm::IsMatch\fP (const KeyType &key1, const KeyType &key2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
NOT YET DOCUMENTED\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
