.TH "DwmReadable.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmReadable.hh \- \fBDwm::Readable\fP pure virtual class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'DwmDescriptorIOCapable\&.hh'\fP
.br
\fR#include 'DwmFileIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamIOCapable\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Readable\fP"
.br
.RI "This class defines an interface for classes that can read their contents from an istream, file descriptor or FILE pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Readable\fP pure virtual class definition\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
