.TH "DwmSocket.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmSocket.hh \- \fBDwm::Socket\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <sys/un\&.h>\fP
.br
\fR#include <netinet/in\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'DwmDescriptor\&.hh'\fP
.br
\fR#include 'DwmIpv4Address\&.hh'\fP
.br
\fR#include 'DwmIpv6Address\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Socket\fP"
.br
.RI "This class abstracts a UNIX socket descriptor\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Socket\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
