.TH "DwmSysLogger.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmSysLogger.hh \- \fBDwm::SysLogger\fP class definition and \fBSyslog()\fP macro\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <errno\&.h>\fP
.br
\fR#include <stdarg\&.h>\fP
.br
\fR#include <syslog\&.h>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <version>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'DwmPortability\&.hh'\fP
.br
\fR#include <format>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::SysLogger\fP"
.br
.RI "This class encapsulates syslog logging in global scope (all members are static)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSyslog\fP(\&.\&.\&.)     \fBDwm::SysLogger::Log\fP(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)"
.br
.RI "Used just like syslog(), but calls \fBDwm::SysLogger::Log()\fP to allow the filename, line number and function name to be logged automatically and the priority tag text provided by \fBDwm::SysLogger\fP\&. "
.ti -1c
.RI "#define \fBFSyslog\fP(\&.\&.\&.)       Dwm::SysLogger::FmtLog(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)"
.br
.RI "Like \fBSyslog()\fP but the format string (second argument) is a std::format format string\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::SysLogger\fP class definition and \fBSyslog()\fP macro\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define FSyslog( \&.\&.\&.)       Dwm::SysLogger::FmtLog(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)"

.PP
Like \fBSyslog()\fP but the format string (second argument) is a std::format format string\&. Unfortunately some of the popular Linux distributions are way behind on a libstdc++ that has <format>\&. It's May 26, 2024 and Ubuntu 24\&.04 and Raspberry Pi 12 (bookwork) don't have the C++20 features that are needed\&. On such platforms, I use libfmt instead\&. 
.SS "#define Syslog( \&.\&.\&.)     \fBDwm::SysLogger::Log\fP(__FILE__,__LINE__,__PRETTY_FUNCTION__,__VA_ARGS__)"

.PP
Used just like syslog(), but calls \fBDwm::SysLogger::Log()\fP to allow the filename, line number and function name to be logged automatically and the priority tag text provided by \fBDwm::SysLogger\fP\&. Note this requires variadic macros, but g++ and clang++ support them\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
