.TH "DwmSignal.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmSignal.hh \- \fBDwm::Signal\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <signal\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::Signal\fP"
.br
.RI "This class encapsulates a signal\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Signal\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
