.TH "DwmSvnTag.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmSvnTag.hh \- \fBDwm::SvnTag\fP class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::SvnTag\fP"
.br
.RI "Trivial class used to fetch an assumed SVN tag name from a repository path (in a Subversion keyword)\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::SvnTag\fP class declaration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
