.TH "DwmStringConverter.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmStringConverter.hh \- \fBDwm::StringConverter\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'DwmStringUtils\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::StringConverter\fP"
.br
.RI "Encapsulates conversion from a string to another type\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::StringConverter\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
