.TH "DwmTermios.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmTermios.hh \- \fBDwm::Termios\fP and supporting classes definitions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <inttypes\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDwm::TermioFlagInfo_t\fP"
.br
.RI "Holds termios flag values and names\&. "
.ti -1c
.RI "class \fBDwm::TermioFlags\fP"
.br
.RI "Base class for input, output, control and local termio flags\&. "
.ti -1c
.RI "class \fBDwm::TermioInputFlags\fP"
.br
.RI "Encapsulates termios input flags\&. "
.ti -1c
.RI "class \fBDwm::TermioOutputFlags\fP"
.br
.RI "Encapsulates termios output flags\&. "
.ti -1c
.RI "class \fBDwm::TermioControlFlags\fP"
.br
.RI "Encapsulates termios control flags\&. "
.ti -1c
.RI "class \fBDwm::TermioLocalFlags\fP"
.br
.RI "Encapsulates termios local flags\&. "
.ti -1c
.RI "class \fBDwm::Termios\fP"
.br
.RI "Encapsulates a struct termios\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::Termios\fP and supporting classes definitions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
