.TH "DwmTerminalTricks.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmTerminalTricks.hh \- \fBDwm::TerminalTricks\fP class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::TerminalTricks\fP"
.br
.RI "Encapsulate simple terminal tricks (bold and underscore)\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::TerminalTricks\fP class declaration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
