.TH "DwmTimeUtil.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmTimeUtil.hh \- \fBDwm::TimeUtil\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <time\&.h>\fP
.br
\fR#include <sys/time\&.h>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::TimeUtil\fP"
.br
.RI "This class is just a collection of time utility functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::TimeUtil\fP class definition\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
