.TH "DwmTimeInterval.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmTimeInterval.hh \- \fBDwm::TimeInterval\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assert\&.h>\fP
.br
\fR#include <utility>\fP
.br
\fR#include 'DwmTimeValue\&.hh'\fP
.br
\fR#include 'DwmDescriptorIOCapable\&.hh'\fP
.br
\fR#include 'DwmFileIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamedLengthCapable\&.hh'\fP
.br
\fR#include 'DwmGZIOCapable\&.hh'\fP
.br
\fR#include 'DwmBZ2IOCapable\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::TimeInterval\fP"
.br
.RI "This class encapsulates a time interval\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::TimeInterval\fP class definition\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
