.TH "DwmThreadPool.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmThreadPool.hh \- \fBDwm::ThreadPool\fP class template\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <concepts>\fP
.br
\fR#include <condition_variable>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::ThreadPool< N, F, Args >\fP"
.br
.RI "Encapsulate a trivial thread pool\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::ThreadPool\fP class template\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
