.TH "DwmTimeValue64.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmTimeValue64.hh \- \fBDwm::TimeValue64\fP class definition\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/time\&.h>\fP
.br
\fR#include <sys/timespec\&.h>\fP
.br
\fR#include <sys/uio\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'DwmTimeValue\&.hh'\fP
.br
\fR#include 'DwmDescriptorIOCapable\&.hh'\fP
.br
\fR#include 'DwmFileIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamIOCapable\&.hh'\fP
.br
\fR#include 'DwmStreamedLengthCapable\&.hh'\fP
.br
\fR#include 'DwmGZIOCapable\&.hh'\fP
.br
\fR#include 'DwmBZ2IOCapable\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::TimeValue64\fP"
.br
.RI "This class encapsulates a time value beyond the UNIX epoch, with microsecond granularity\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDwm::TimeValue64\fP \fBoperator+\fP (const \fBDwm::TimeValue64\fP &tv1, const \fBDwm::TimeValue64\fP &tv2)"
.br
.ti -1c
.RI "\fBDwm::TimeValue64\fP \fBoperator\-\fP (const \fBDwm::TimeValue64\fP &tv1, const \fBDwm::TimeValue64\fP &tv2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::TimeValue64\fP class definition\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
