.TH "DwmVariantFromIndex.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmVariantFromIndex.hh \- \fBDwm::VariantFromIndex\fP function template\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <variant>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Ts> std::variant< Ts\&.\&.\&. > \fBDwm::VariantFromIndex\fP (size_t index)"
.br
.RI "Returns a variant type \fRV\fP whose contents are set to a default constructed value of the type at \fRindex\fP in the variant\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::VariantFromIndex\fP function template\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
