.TH "DwmXmlAttribute.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmXmlAttribute.hh \- Dwm::Xml::Attribute class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <string>\fP
.br

.SH "Detailed Description"
.PP 
Dwm::Xml::Attribute class declaration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
