.TH "DwmXDRUtils.hh" 3 "libDwm-0.0.20240716" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DwmXDRUtils.hh \- \fBDwm::XDRUtils\fP class declaration\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDwm::XDRUtils\fP"
.br
.RI "Wrapper for XDR encode/decode functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDwm::XDRUtils\fP class declaration\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel W\&. McRobb 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libDwm-0\&.0\&.20240716 from the source code\&.
